# Generated by Django 5.2 on 2025-05-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredreport',
            name='student_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='student_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='assessvalidity',
            name='gai_score',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='facultyci',
            name='gai_score',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='facultyci',
            name='instr_first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='facultyci',
            name='instr_last_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='programci',
            name='gai_score',
            field=models.CharField(max_length=250),
        ),
    ]
